FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api-server ./api

FROM alpine:3
WORKDIR /app
COPY --from=build /app/api-server .
COPY --from=build /app/api/static/ api/static/
EXPOSE 8080
ENTRYPOINT ["/app/api-server"]
