FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o kgs-server ./kgs

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=build /app/kgs-server .
EXPOSE 8081
ENTRYPOINT ["/app/kgs-server"]
